# 2.1からOrbsが使えるぞ
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16

jobs:
  test:
    # CircleCIでdocker-composeを使用するため、ホストマシンにはVMを使用する
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      # - run: docker-compose -f ./docker-compose.yaml up -d
      # - run: npm install
      # - run: sleep 10
      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}
      # - run: npm run test
      # - run: npm run coverage

  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build:lambda
      - run: npm run build:lambda-layer
      - persist_to_workspace:
          root: ~/repo/
          paths:
            - lambda_layer.zip
            - built/
            - scripts/

  deploy:
    executor: aws-cli/default
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo/
      - run: sh scripts/deploy_lambda_layer.sh
      - run: sh scripts/deploy_lambda.sh

aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run: echo "Run your code here"      

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test      
      - deploy:
          requires:
            - build