version: 2
jobs:
  test:
    # CircleCIでdocker-composeを使用するため、ホストマシンにはVMを使用する
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      # - run: docker-compose -f ./docker-compose.yaml up -d
      # - run: npm install
      # - run: sleep 10
      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}
      # - run: npm run test
      # - run: npm run coverage

  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build:lambda
      - run: npm run build:lambda-layer
      - persist_to_workspace:
          root: ~/repo/
          paths:
            - lambda_layer.zip
            - built/

  deploy:
    docker:
      - image: circleci/python:3.7.4-stretch
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo/

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build
      - deploy
